apiVersion: v2
name: ingress-nginx
description: ingress-nginx chart
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: ingress-nginx
    version: "4.12.2"
    repository: https://kubernetes.github.io/ingress-nginx
